export enum EDifficultyLevel {
  NHAN_BIET = "NHAN_BIET",
  THONG_HIEU = "THONG_HIEU",
  VAN_DUNG = "VAN_DUNG",
  VAN_DUNG_CAO = "VAN_DUNG_CAO",
}

export enum EKnowledgeDomain {
  HAM_SO = "HAM_SO",
  MU_LOGARIT = "MU_LOGARIT",
  NGUYEN_HAM_TICH_PHAN = "NGUYEN_HAM_TICH_PHAN",
  SO_PHUC = "SO_PHUC",
  HINH_HOC_KHONG_GIAN = "HINH_HOC_KHONG_GIAN",
  XAC_SUAT_THONG_KE = "XAC_SUAT_THONG_KE",
  TOAN_HOC_THUC_TE = "TOAN_HOC_THUC_TE",
  TO_HOP_XAC_SUAT = "TO_HOP_XAC_SUAT",

  CAU_TAO_NGUYEN_TU = "CAU_TAO_NGUYEN_TU",
  LIEN_KET_HOA_HOC = "LIEN_KET_HOA_HOC",
  PHAN_UNG_OXI_HOA_KHU = "PHAN_UNG_OXI_HOA_KHU",
  CAN_BANG_HOA_HOC = "CAN_BANG_HOA_HOC",
  KIM_LOAI = "KIM_LOAI",
  DIEN_HOA_HOC = "DIEN_HOA_HOC",
  ESTE_LIPIT = "ESTE_LIPIT",
  CARBOHYDRATE = "CARBOHYDRATE",
  AMINE_AMINO_ACID_PROTEIN = "AMINE_AMINO_ACID_PROTEIN",
  POLYMER = "POLYMER",
  PHO_HOA_HOC = "PHO_HOA_HOC",
  HOA_HOC_THUC_TIEN = "HOA_HOC_THUC_TIEN",

  TE_BAO_HOC = "TE_BAO_HOC",
  CO_CHE_DI_TRUYEN_PHAN_TU = "CO_CHE_DI_TRUYEN_PHAN_TU",
  QUY_LUAT_DI_TRUYEN = "QUY_LUAT_DI_TRUYEN",
  BIEN_DI = "BIEN_DI",
  DI_TRUYEN_QUAN_THE = "DI_TRUYEN_QUAN_THE",
  UNG_DUNG_DI_TRUYEN = "UNG_DUNG_DI_TRUYEN",
  TIEN_HOA = "TIEN_HOA",
  SINH_LY_THUC_VAT = "SINH_LY_THUC_VAT",
  SINH_LY_DONG_VAT = "SINH_LY_DONG_VAT",
  SINH_THAI_HOC = "SINH_THAI_HOC",
  SINH_HOC_THUC_TE = "SINH_HOC_THUC_TE",
}

export enum EExamPart {
  I = "I",
  II = "II",
  III = "III",
}

export enum EExamSubject {
  MATH = "MATH",
  CHEMISTRY = "CHEMISTRY",
  BIOLOGY = "BIOLOGY",
}
